// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDJMAqLM_RyQhtE7qlUUbzO2zx94GeF5NQ',
    appId: '1:267712889643:web:23d69e2eac9630dd503b6e',
    messagingSenderId: '267712889643',
    projectId: 'fir-flutter-codelab-4b4a2',
    authDomain: 'fir-flutter-codelab-4b4a2.firebaseapp.com',
    storageBucket: 'fir-flutter-codelab-4b4a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCFsZNbTQvzs2i1B0QmuOgqNO5alaHwhJI',
    appId: '1:267712889643:android:358c7e16282a16e0503b6e',
    messagingSenderId: '267712889643',
    projectId: 'fir-flutter-codelab-4b4a2',
    storageBucket: 'fir-flutter-codelab-4b4a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAj520ft8lnKDMD5UR8WSRPgXRDSrRrTi4',
    appId: '1:267712889643:ios:9996c307319270cc503b6e',
    messagingSenderId: '267712889643',
    projectId: 'fir-flutter-codelab-4b4a2',
    storageBucket: 'fir-flutter-codelab-4b4a2.appspot.com',
    iosClientId: '267712889643-brsh0ubn2rdur8sg15kp4qdnie3gursn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAj520ft8lnKDMD5UR8WSRPgXRDSrRrTi4',
    appId: '1:267712889643:ios:9996c307319270cc503b6e',
    messagingSenderId: '267712889643',
    projectId: 'fir-flutter-codelab-4b4a2',
    storageBucket: 'fir-flutter-codelab-4b4a2.appspot.com',
    iosClientId: '267712889643-brsh0ubn2rdur8sg15kp4qdnie3gursn.apps.googleusercontent.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
